### ISSUE TITLE
Drag & drop not working

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#573] opened 2021-03-26 03:35 UTC
Cannot use drag & drop feature to reorder subtasks or input fields.

**Comment by maxinteger** [comment] 2021-04-07 20:26
@vektor8891 
1. this is not a bug since this feature is not exists at the moment
2. you create another task about the subtask reordering #582 

So I close this one and I create a feature task about reordering input fields

**Closed by maxinteger** 2021-04-07 20:26 UTC
Labels: C - Admin, P - Major, T - Bug
